//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DkiMuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DkiMuonSach()
        {
            this.ChiTietDks = new HashSet<ChiTietDk>();
        }
    
        public int MaDK { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayDKMuon { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public Nullable<int> Tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDk> ChiTietDks { get; set; }
        public virtual LOGIN_DG LOGIN_DG { get; set; }
    }
}
