//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoSachThanhLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoSachThanhLy()
        {
            this.ChiTietPTLs = new HashSet<ChiTietPTL>();
        }
    
        public string TenSachtl { get; set; }
        public string TheLoaitl { get; set; }
        public string TacGiatl { get; set; }
        public string NgonNgutl { get; set; }
        public string NXBtl { get; set; }
        public Nullable<int> NamXBtl { get; set; }
        public Nullable<int> GiaSachtl { get; set; }
        public Nullable<int> SoLuongthanhly { get; set; }
        public int masach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPTL> ChiTietPTLs { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
