//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuTra()
        {
            this.ChiTietPTs = new HashSet<ChiTietPT>();
        }
    
        public int MaPT { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaThe { get; set; }
        public Nullable<int> MaPM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPT> ChiTietPTs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual TheDocGia TheDocGia { get; set; }
    }
}
