//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThanhLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThanhLy()
        {
            this.ChiTietPTLs = new HashSet<ChiTietPTL>();
        }
    
        public int MaPTL { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
        public Nullable<int> MaDV { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPTL> ChiTietPTLs { get; set; }
        public virtual DonViTL DonViTL { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
